# FROM node:16
FROM --platform=linux/amd64 node:16-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
# RUN npm install --production
RUN npm ci
# RUN npm run build

# Bundle app source
COPY dist/apps/linter-server /usr/src/app

EXPOSE 3333
CMD [ "node", "main.js" ]