# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-tdp-openapi-linter(test)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://jbend.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f28f59e43fc847859107b8a8fd646a49 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c2ba47d87ad34be9a66d81ba074aab38 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jbend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f28f59e43fc847859107b8a8fd646a49 }}/tdp-openapi-linter:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'test'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-tdp-openapi-linter'
        slot-name: 'test'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_221062ecab534d12b1adca173ff85a86 }}
        images: 'jbend.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f28f59e43fc847859107b8a8fd646a49 }}/tdp-openapi-linter:${{ github.sha }}'